

import Foundation

class ViewIdentifiers {
    
    // View controller idenitifiers
    public static let VC_MAIN = "MainVC"
    public static let VC_SIDE_MENU = "SideMenuVC"
    public static let VC_TRANSACTION_LOGGING = "TransactionLoggingVC"
    public static let VC_TRANSACTION_DETAILS = "TransactionDetailsVC"
    public static let VC_TRANSACTION = "TransactionVC"
    public static let VC_TRANSACTION_VIEW = "TransactionViewModeVC"
    public static let VC_DASHBOARD = "DashboardVC"
    public static let VC_DASHBOARD_ACCOUNTS = "DashboardAccountsVC"
    public static let VC_DASHBOARD_INCOME = "DashboardIncomeVC"
    public static let VC_DASHBOARD_EXPENSE = "DashboardExpenseVC"
    public static let VC_DASHBOARD_BUDGET = "DashboardBudgetVC"
    public static let VC_CHOOSE_CATEGORY = "ChooseCategoryVC"
    public static let VC_BUDGET_PAGE = "BudgetPageVC"
    public static let VC_BUDGET = "BudgetVC"
    public static let VC_ADD_BUDGET = "AddBudgetVC"
    public static let VC_EVENTS = "EventsVC"
    public static let VC_ADD_EVENT = "AddEventVC"
    public static let VC_EVENT_LEARN_MORE = "EventLearnMoreVC"
    public static let VC_EVENT_TRANSACTIONS = "EventTransactionsVC"
    public static let VC_ADD_ACCOUNT = "AddAccountVC"
    public static let VC_SELECT_PERSON = "SelectPersonVC"
    public static let VC_PFM_PAGE = "PfmLandingPageVC"
    public static let VC_PFM_LANDING = "PfmLandingVC"
    public static let VC_SELECT_CURRENCY = "SelectCurrencyVC"
    public static let VC_CHOOSE_BANK = "ChooseBankVC"
    public static let VC_ACCOUNT_BALANCE = "AccountBalanceVC"
    public static let VC_SAVING = "SavingsVC"
    public static let VC_ADD_SAVING = "AddSavingVC"
    public static let VC_SAVING_TRANSACTIONS = "SavingTransactionsVC"
    public static let VC_ADD_SAVING_TRANSACTION = "AddSavingTransactionVC"
    public static let VC_ACTIVITY_PAGE = "ActivityPageVC"
    public static let VC_ACTIVITY = "ActivityDetailsVC"
    public static let VC_FILTER = "FilterVC"
    public static let VC_SEARCH_ACTIVITY = "SearchActivityVC"
    public static let VC_RECURRING_TRANSACTION = "RecurringTransactionVC"
    public static let VC_GLOBAL_SEARCH = "GlobalSearchVC"
    public static let VC_NOTIFICATION = "NotificationVC"
    public static let VC_SAVINGS_LEARN_MORE = "SavingsLearnMoreVC"
    public static let VC_SETTINGS = "SettingsVC"
    public static let VC_PASSCODE = "PasscodeVC"
    public static let VC_BACKUP = "BackupRestoreVC"
    public static let VC_REMINDER = "ReminderVC"
    public static let VC_ADD_REMINDER = "AddReminderVC"
    public static let VC_TRAVEL_MODE = "TravelModeVC"
    public static let VC_GET_STARTED = "GetStartedVC"
    public static let VC_TERMS_AND_CONDITIONS = "TermsAndConditionsVC"
    public static let VC_PHONE_VERIFICATION = "PhoneVerificationVC"
    public static let VC_SIGNUP_DETAILS = "SignupDetailsVC"
    public static let VC_USER_TYPE = "UserTypeVC"
    public static let VC_USER_INTERESTS = "UserInterestsVC"
    public static let VC_USER_LOCATION = "UserLocationVC"
    public static let VC_WALKTHROUGH = "WalkthroughVC"
    public static let VC_ALL_ACCOUNTS = "AccountBalancesVC"
    public static let VC_PROFILE = "ProfileVC"
    public static let VC_FLYER_RETAILERS = "FlyerRetailersVC"
    public static let VC_FLYER = "FlyersVC"
    public static let VC_FLYER_WEBVIEW = "FlyerWebViewVC"
    public static let VC_FLYER_DETAILS = "FlyerDetailsVC"
    public static let VC_WISHLIST = "WishlistVC"
    public static let VC_OFFERS = "OffersVC"
    public static let VC_DEAL_DETAILS = "DealDetailsVC"
    public static let VC_ADD_REVIEW = "AddReviewVC"
    public static let VC_DEAL_SEARCH = "DealSearchVC"
    public static let VC_OFFER_DETAILS = "OfferDetailsVC"
    public static let VC_FILTER_DEALS = "DealsFilterVC"
    public static let VC_SEARCH_BRAND = "SearchBrandVC"
    public static let VC_FLYER_ALL_DEALS = "FlyerAllDealsVC"
    public static let VC_FLYER_FILTER = "FlyerFilterVC"
    public static let VC_FLYER_CATEGORY = "FilterCategoryVC"
    public static let VC_FLYER_RETAILER = "FilterRetailersVC"
    public static let VC_FLYER_SEARCH = "FlyerSearchVC"
    public static let VC_BUY_NOW = "BuyNowVC"
    public static let VC_CATEGORIES = "CategoriesVC"
    public static let VC_ADD_CATEGORY = "AddCategoryVC"
    public static let VC_PLACES = "PlacesVC"
    public static let VC_CHARTS = "ChartsPageVC"
    public static let VC_BACKUPDETAIL = "BackupDetailsVC"
    public static let VC_BACKMAINVC = "BackupMainVC"
    public static let VC_RESTOREVC = "RestoreVC"
    public static let VC_BACKUP_MESSAGE = "BackupMessageVC"
    public static let VC_NOTIFICATION_MESSAGE = "BackupNotificationVC"
    public static let VC_SKIP_MESSAGE = "SkipRestoreMessage"
    public static let VC_WIPE_ALERT = "WipeAllDataAlert"
    public static let VC_SIGNUP_ALERT = "SignupContinueAlertVC"
    public static let VC_HK_NIT = "HKNITController"
    public static let VC_HK_NITINTRODUCTION = "NITIntroductionController"
    public static let VC_HK_NITINFORMATION = "NITInformationController"
    public static let VC_HK_SUCCESSSCREEN = "NITSuccessScreen"
    public static let VC_HK_NIT_INVESTMENTFORM = "InvestmentForm"

    

    
    
    
    

    // Storyboard identifiers
    public static let SB_DASHBOARD = "Dashboard"
    public static let SB_TRANSACTION = "Transaction"
    public static let SB_BUDGET = "Budget"
    public static let SB_EVENT = "Event"
    public static let SB_ACCOUNT = "Account"
    public static let SB_PFM = "PFMLanding"
    public static let SB_SAVING = "Saving"
    public static let SB_ACTIVITY = "Activity"
    public static let SB_SEARCH = "Search"
    public static let SB_SETTINGS = "Settings"
    public static let SB_REMINDER = "Reminder"
    public static let SB_TRAVEL_MODE = "TravelMode"
    public static let SB_ONBOARDING = "Onboarding"
    public static let SB_MAIN = "Main"
    public static let SB_FLYER = "Flyer"
    public static let SB_WISHLIST = "Wishlist"
    public static let SB_DEAL = "Deals"
    public static let SB_CATEGORY = "Category"
    public static let SB_CHARTS = "Charts"
    public static let SB_PLACES = "Places"
    public static let SB_BACKUP = "Backup"
    public static let SB_HKNIT = "HKNIT"
}
